name: places
description: amaizing world

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^0.23.0+1
  google_fonts: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - res/
  fonts:
    - family: Roboto
      fonts:
        - asset: res/fonts/Roboto/Roboto-Light.ttf
        - asset: res/fonts/Roboto/Roboto-Bold.ttf
        - asset: res/fonts/Roboto/Roboto-Italic.ttf
          weight: 700
